spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxxxxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: 
    password: 
  session:
    timeout: 86400
server:
  address: 0.0.0.0
